package app.isaruff.budgettracker.domain.model

enum class Currency(val code: String, val symbol: String, val fullName: String) {
    USD("USD", "$", "United States Dollar"),
    EUR("EUR", "€", "Euro"),
    GBP("GBP", "£", "British Pound Sterling"),
    JPY("JPY", "¥", "Japanese Yen"),
    CHF("CHF", "Fr", "Swiss Franc"),
    CAD("CAD", "$", "Canadian Dollar"),
    AUD("AUD", "$", "Australian Dollar"),
    NZD("NZD", "$", "New Zealand Dollar"),
    CNY("CNY", "¥", "Chinese Yuan"),
    HKD("HKD", "$", "Hong Kong Dollar"),
    SGD("SGD", "$", "Singapore Dollar"),
    SEK("SEK", "kr", "Swedish Krona"),
    NOK("NOK", "kr", "Norwegian Krone"),
    DKK("DKK", "kr", "Danish Krone"),
    PLN("PLN", "zł", "Polish Zloty"),
    CZK("CZK", "Kč", "Czech Koruna"),
    HUF("HUF", "Ft", "Hungarian Forint"),
    RUB("RUB", "₽", "Russian Ruble"),
    INR("INR", "₹", "Indian Rupee"),
    PKR("PKR", "₨", "Pakistani Rupee"),
    BDT("BDT", "৳", "Bangladeshi Taka"),
    IDR("IDR", "Rp", "Indonesian Rupiah"),
    MYR("MYR", "RM", "Malaysian Ringgit"),
    THB("THB", "฿", "Thai Baht"),
    KRW("KRW", "₩", "South Korean Won"),
    VND("VND", "₫", "Vietnamese Dong"),
    PHP("PHP", "₱", "Philippine Peso"),
    AED("AED", "د.إ", "United Arab Emirates Dirham"),
    SAR("SAR", "﷼", "Saudi Riyal"),
    QAR("QAR", "﷼", "Qatari Riyal"),
    KWD("KWD", "د.ك", "Kuwaiti Dinar"),
    BHD("BHD", "ب.د", "Bahraini Dinar"),
    OMR("OMR", "﷼", "Omani Rial"),
    TRY("TRY", "₺", "Turkish Lira"),
    ILS("ILS", "₪", "Israeli New Shekel"),
    EGP("EGP", "£", "Egyptian Pound"),
    ZAR("ZAR", "R", "South African Rand"),
    NGN("NGN", "₦", "Nigerian Naira"),
    GHS("GHS", "₵", "Ghanaian Cedi"),
    KES("KES", "Sh", "Kenyan Shilling"),
    UGX("UGX", "Sh", "Ugandan Shilling"),
    TZS("TZS", "Sh", "Tanzanian Shilling"),
    MAD("MAD", "د.م.", "Moroccan Dirham"),
    TND("TND", "د.ت", "Tunisian Dinar"),
    ARS("ARS", "$", "Argentine Peso"),
    BRL("BRL", "R$", "Brazilian Real"),
    CLP("CLP", "$", "Chilean Peso"),
    COP("COP", "$", "Colombian Peso"),
    MXN("MXN", "$", "Mexican Peso"),
    PEN("PEN", "S/", "Peruvian Sol"),
    UYU("UYU", "U", "Uruguayan Peso"),
    BOB("BOB", "Bs", "Bolivian Boliviano"),
    PYG("PYG", "₲", "Paraguayan Guarani"),
    DOP("DOP", "RD$", "Dominican Peso"),
    CRC("CRC", "₡", "Costa Rican Colón"),
    GTQ("GTQ", "Q", "Guatemalan Quetzal"),
    HNL("HNL", "L", "Honduran Lempira"),
    NIO("NIO", "C$", "Nicaraguan Córdoba"),
    BZD("BZD", "BZ$", "Belize Dollar"),
    JMD("JMD", "J$", "Jamaican Dollar"),
    TTD("TTD", "TT$", "Trinidad and Tobago Dollar"),
    LKR("LKR", "Rs", "Sri Lankan Rupee"),
    NPR("NPR", "Rs", "Nepalese Rupee"),
    MMK("MMK", "Ks", "Myanmar Kyat"),
    KHR("KHR", "៛", "Cambodian Riel"),
    LAK("LAK", "₭", "Lao Kip"),
    MNT("MNT", "₮", "Mongolian Tögrög"),
    IRR("IRR", "﷼", "Iranian Rial"),
    IQD("IQD", "ع.د", "Iraqi Dinar"),
    LBP("LBP", "ل.ل", "Lebanese Pound"),
    JOD("JOD", "د.ا", "Jordanian Dinar"),
    SDG("SDG", "£", "Sudanese Pound"),
    ETB("ETB", "Br", "Ethiopian Birr"),
    DZD("DZD", "د.ج", "Algerian Dinar"),
    XOF("XOF", "CFA", "West African CFA Franc"),
    XAF("XAF", "CFA", "Central African CFA Franc"),
    MUR("MUR", "₨", "Mauritian Rupee"),
    SCR("SCR", "₨", "Seychellois Rupee"),
    MZN("MZN", "MT", "Mozambican Metical"),
    BWP("BWP", "P", "Botswana Pula"),
    ZMW("ZMW", "ZK", "Zambian Kwacha"),
    MWK("MWK", "MK", "Malawian Kwacha");

    companion object Companion {
        fun fromCode(code: String): Currency =
            entries.find { it.code.equals(code, ignoreCase = true) } ?: error("Currency not defined")
    }
}
